name: Release og-custom-paused-icon Module

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node_version: 22

jobs:
  set_version:
    runs-on: ubuntu-latest

    outputs:
      previous: ${{ steps.versions.outputs.previous }}
      current: ${{ steps.versions.outputs.current }}
      should_release: ${{ steps.versions.outputs.should_release }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Get Previous tag for og-custom-paused-icon"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          prefix: "v"
        continue-on-error: true

      - name: Get version from module.json
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "module.json"
          prop_path: "version"

      - name: Set versions variables
        id: versions
        run: |
          previous="${{ steps.previoustag.outputs.tag || 'v0.0.0' }}"
          current="${{ steps.version.outputs.prop }}"

          # For pull requests, suffix the version so we publish prereleases without touching tags
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then
            sha_short=$(git rev-parse --short "$GITHUB_SHA")
            current="${current}-${sha_short}"
          fi

          # Remove leading 'v' from previous tag for comparison
          previous_clean=$(echo "$previous" | sed 's/^v//')

          echo "previous=$previous_clean" >> $GITHUB_OUTPUT
          echo "current=$current" >> $GITHUB_OUTPUT
          if [ "$previous_clean" != "$current" ]; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Output values
        run: |
          echo "Previous: ${{ steps.versions.outputs.previous }}"
          echo "Current: ${{ steps.versions.outputs.current }}"
          echo "Should release: ${{ steps.versions.outputs.should_release }}"

  build:
    needs: set_version
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Build the module
        run: npm run build

      - name: Upload dist directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: og-custom-paused-icon-dist
          path: dist

  release_to_github:
    needs: [build, set_version]
    runs-on: ubuntu-latest
    if: ${{ needs.set_version.outputs.should_release == 'true' }}
    permissions:
      contents: write

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: og-custom-paused-icon-dist
          path: ./dist

      - name: Create Module Archive from the dist directory
        run: |
          cd dist
          zip -r ../og-custom-paused-icon-v${{ needs.set_version.outputs.current }}.zip .

      - name: Create the GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.set_version.outputs.current }}
          prerelease: ${{ github.event_name == 'pull_request' }}
          name: og-custom-paused-icon v${{ needs.set_version.outputs.current }}
          body: |
            ## og-custom-paused-icon v${{ needs.set_version.outputs.current }}

            ### Installation for Foundry VTT v13

            **Manifest URL:**
            ```
            https://github.com/${{ github.repository }}/releases/download/v${{ needs.set_version.outputs.current }}/module.json
            ```

            **Direct Download:**
            - [og-custom-paused-icon-v${{ needs.set_version.outputs.current }}.zip](https://github.com/${{ github.repository }}/releases/download/v${{ needs.set_version.outputs.current }}/og-custom-paused-icon-v${{ needs.set_version.outputs.current }}.zip)

            ### Changes
            - Version bump to ${{ needs.set_version.outputs.current }}
          files: |
            og-custom-paused-icon-v${{ needs.set_version.outputs.current }}.zip
            dist/module.json
